Repository enjoythevue/website, pull requests merged in 2020-01, with the labels that each got.

#73 Use CMS provided sponsor link value.
  src/templates/Episode.vue
Labels: content-management, enhancement

#67 Make some design updates to sponsorship area to make it look more unified.
  src/components/SponsorshipBox.vue
  src/templates/Episode.vue
Labels: enhancement

#74 Expand media player features
  src/components/MediaPlayer.vue
  src/image-components/SpeakerIcon.vue
  src/templates/Episode.vue
Labels: media-player
